# Generated by Django 3.2.3 on 2024-10-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiInformacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=75)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('direccion', models.TextField(max_length=250)),
                ('telefono', models.TextField(max_length=13)),
                ('email', models.TextField(max_length=35)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1)),
            ],
        ),
    ]
