# Generated by Django 3.2.3 on 2024-10-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miinformacion',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
    ]
