# Generated by Django 3.2.3 on 2024-10-11 21:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=250)),
                ('costo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)])),
            ],
        ),
        migrations.CreateModel(
            name='Automovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=75)),
                ('color', models.TextField(choices=[('BLANCO', 'Blanco'), ('NEGRO', 'Negro'), ('ROJO', 'Rojo')], default='NEGRO', max_length=10)),
                ('peso', models.FloatField()),
                ('motor', models.TextField(choices=[('4CIL', '4 cilindros'), ('8CIL', '8 cilindros')], default='4CIL', max_length=4)),
                ('precio', models.FloatField()),
                ('caracteristicas', models.ManyToManyField(to='garaje.Caracteristicas')),
                ('modelo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='garaje.modelo')),
            ],
        ),
    ]
