# Generated by Django 3.2.3 on 2024-10-11 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0002_alter_miinformacion_fecha_nacimiento'),
        ('garaje', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automovil', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='garaje.automovil')),
                ('cliente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='participante.miinformacion')),
            ],
        ),
    ]
